### ISSUE TITLE
[Feature] 경로 데이터 가공

### ISSUE THREAD

**Issue by 0unk0** [SesacWannaSIT/WannaSIT#24]
## Description
경로별 추천 호차 랭킹, 호차 디테일 데이터를 제공하기 위한 경로 데이터 가공

## To-do
- [x] 전체 역 리스트 가져오기
- [x] 출발/도착역에 따른 역 리스트(+ 내외선 계산)
- [x] 출발 이후 역 리스트 별 시간/분 대 계산
- [x] DB에서 출발/도착역까지의 내외선, 역, 요일, 시간/분 대 필터링 된 데이터 가져오기
