### ISSUE TITLE
[Feature] 호차 정보

### ISSUE THREAD

**Issue by 0unk0** [SesacWannaSIT/WannaSIT#34]
## Description
경로, 칸 선택(랭킹 선택) 이후 호차 정보(디테일)

## To-do
- [x] 칸 유지 시 역 별 착석 가능성 분류
- [x] 칸 이동 시 역 별 착석 가능성 높은 칸 Top2
- [x] 착석 꿀팁
- [x] 응답 데이터로 가공
