### ISSUE TITLE
[Feature] 지하철 데이터 처리 및 DB 구축 배치 프로그램

### ISSUE THREAD

**Issue by 0unk0** [SesacWannaSIT/WannaSIT#69]
## Description
지하철 데이터 처리 및 DB 구축 프로세스를 하나의 배치 프로그램(ex. batch.js)으로 통합하기 위한 작업

## To-do
- [x] 배치 프로그램 디렉토리 구조화(batchProcessing)
- [x] 디렉토리 변경에 의한 파일 참조 수정
- [x] 배치 파일 작성
